services:
  database:
    image: postgres:16-alpine3.22
    env_file: ./database/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/pg_hba.conf:/tmp/pg_hba.conf
      - ./database/postgresql.conf:/tmp/postgresql.conf
      - ./database/init-db.sh:/usr/local/bin/init-db.sh
    entrypoint: ["/usr/local/bin/init-db.sh"]
    networks:
      - main-network

  app:
    build:
      context: ./app
    entrypoint: "/bin/sh entrypoint.dev.sh"
    volumes:
      - ./app:/app
      - ./app/static:/app/static
      - app_media:/media
    ports:
      - 8000:8000
    depends_on:
      - database
    env_file: ./app/.env
    networks:
      - main-network

volumes:
  postgres_data:
  app_media:

networks:
  main-network:
    name: main-network
